s= "ATCTTTAAGAGTGATTGGGGGAGAACTCACCGACTCTTGGGAACTCTGGGCCCTCGCGACCCCCATCTCCGTTCAACAGAAAATGTAAAGGTAAGACATGGATTAGGCCGTGGGCTCACCTATTTAAACGCGGGCGCTAGTCTGCCAGCTGCTGCCTCCTAACCATCTCCAATGTGCCGATGGCCTGCGCTGCTGGACAACGCCCTCAGTATCACGATACAATACGAGGCTCAATTACGAAACACCGGCGGGGTATACAGTATCATCCTGGTGAACCAGACTGTCGACATACCAGGAATGATGACATTGATGTCTCTCACGTCTCCCTGTGTGTCTGTGACTCCCCTCGTTACAATCGTCTTACATAGTTGATTCTAGTTGTTGATCCCAAGAATATACTATCAAAAGAGGTGTCCGGTTCTGCGTTTTTTTGACCTTAATTCACTTGGCCGAGTGCAACATCTTACTCCGGTAACTTGTCCCAGAGTGGCTGGAACCTTCGCGCAAATGCTTGCATTGTTTCATAACACGCAGGCGCCAGTGGTGTGCGGAATTCACATCCGTAACTAGAGGCTCTGGTATAACGCTAAAAAATGTGCAGGGCTCAGCCTGCACAGTGGTGCAGACGATAAGTGGTTCGGCGTTCTAGTCATTTAGCCCCCACTGAACGATATGTGTCTCTACCAGTAAAGAGCAGGACCCCCGAAGGGTCGCCTGCGAGTATATGGGAGAAGGCAGTCCACCCAGCGGCGGGGCGGTAACAGGGGCATCTAGGTCTGGTGCCGAACGTCGTGGAATATTACATTTTTAGCCAAGTGCTCACTCAGGCGTGATGCGAAGTATAGCGGGGAAGAAAAACTGTGGAAGCCAGATAGGCCCTCGTTTTA"
l= []
for c in s:
	if c == 'G' :
		l.append('C')
	
	elif c == 'A':
		l.append('T')
	
	elif c == 'C':
		l.append('G')
	
	elif c == 'T':
		l.append('A')
		
l.reverse()
st = ''.join(l)
print st

""" How do I add the result into a new string which I can then reverse?"""